# Generated by Django 3.0.3 on 2020-10-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default=3)),
            ],
        ),
    ]
